import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.patient': 'Book Appointment',
    'nav.doctor': 'Doctor Dashboard',
    'nav.pharmacy': 'Pharmacy',
    'nav.beds': 'Bed Management',
    'nav.ambulance': 'Ambulance',
    'nav.login': 'Login',
    'nav.logout': 'Log out',
    'nav.profile': 'Profile',

    // Login Page
    'login.title': 'ClinicCare Login',
    'login.subtitle': 'Access your healthcare portal',
    'login.signin': 'Sign In',
    'login.signup': 'Sign Up',
    'login.description': 'Choose your role and enter your credentials',
    'login.patient': 'Patient',
    'login.doctor': 'Doctor',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.fullName': 'Full Name',
    'login.phone': 'Phone Number',
    'login.signinButton': 'Sign In',
    'login.signupButton': 'Sign Up',
    'login.signingIn': 'Signing in...',
    'login.signingUp': 'Signing up...',
    'login.haveAccount': 'Already have an account?',
    'login.noAccount': "Don't have an account?",
    'login.sessionExpiry': 'Session will expire after 5 minutes of inactivity',
    'login.patientAccess': 'Patient Portal Access:',
    'login.patientDesc': 'Book appointments, view medical history, and manage prescriptions',
    'login.doctorAccess': 'Doctor Portal Access:',
    'login.doctorDesc': 'Manage appointments, write prescriptions, and view patient records',

    // Home Page
    'home.title': 'ClinicCare Management System',
    'home.subtitle': 'Smart queue management, emergency services, and seamless patient care coordination',
    'home.welcomeBack': 'Welcome back',
    'home.myAppointments': 'My Appointments',
    'home.ourServices': 'Our Services',
    'home.bookAppointment': 'Book Appointment',
    'home.doctorPortal': 'Doctor Portal',
    'home.patientsServed': 'Patients Served',
    'home.expertDoctors': 'Expert Doctors',
    'home.hospitalBeds': 'Hospital Beds',
    'home.service247': '24/7 Service',
    'home.always': 'Always',
    'home.patientAppointments': 'Patient Appointments',
    'home.patientAppointmentsDesc': 'Book appointments with preferred doctors and time slots',
    'home.doctorDashboard': 'Doctor Dashboard',
    'home.doctorDashboardDesc': 'Manage appointments, write prescriptions, and patient care',
    'home.pharmacy': 'Pharmacy',
    'home.pharmacyDesc': 'Prescription management and medicine inventory tracking',
    'home.bedManagement': 'Bed Management',
    'home.bedManagementDesc': 'Real-time bed availability and reservation system',
    'home.emergencyAmbulance': 'Emergency Ambulance',
    'home.emergencyAmbulanceDesc': 'Smart dispatch system for nearest ambulance',
    'home.smartQueue': 'Smart Queue Algorithm',
    'home.smartQueueDesc': 'Intelligent prioritization for optimal patient care',
    'home.priority1': 'st',
    'home.priority2': 'nd',
    'home.priority3': 'rd',
    'home.urgencyLevel': 'Urgency Level',
    'home.criticalCases': 'Critical cases prioritized',
    'home.seniorCitizens': 'Senior Citizens',
    'home.age60Plus': 'Age 60+ gets priority',
    'home.appointmentTime': 'Appointment Time',
    'home.earlierSlots': 'Earlier slots served first',

    // Patient Booking
    'booking.title': 'Book Appointment',
    'booking.subtitle': 'Fill in your details to schedule a consultation',
    'booking.patientName': 'Patient Name',
    'booking.enterName': 'Enter full name',
    'booking.age': 'Age',
    'booking.enterAge': 'Enter age',
    'booking.phone': 'Phone Number',
    'booking.enterPhone': 'Enter phone',
    'booking.email': 'Email',
    'booking.enterEmail': 'Enter email address',
    'booking.issue': 'Medical Issue / Reason',
    'booking.selectSymptom': 'Select your symptom',
    'booking.describeSymptom': 'Describe your symptoms or reason for visit',
    'booking.urgency': 'Urgency Level',
    'booking.urgencyLow': 'Low - Routine checkup',
    'booking.urgencyMedium': 'Medium - Standard consultation',
    'booking.urgencyHigh': 'High - Urgent attention needed',
    'booking.urgencyCritical': 'Critical - Emergency',
    'booking.preferredDoctor': 'Preferred Doctor',
    'booking.selectDoctor': 'Select a doctor',
    'booking.timeSlot': 'Preferred Time Slot',
    'booking.continuePayment': 'Continue to Payment',
    'booking.fillAllFields': 'Please fill in all fields',
    'booking.validAge': 'Please enter a valid age',
    'booking.bookingSuccess': 'Appointment booked successfully!',
    'booking.pendingApproval': 'Your appointment is pending doctor approval.',
    'booking.appointmentId': 'Appointment ID',
    'booking.consultationFee': 'Consultation fee for',
    'booking.urgencyAppointment': 'urgency appointment',
    'booking.invoiceDescription': 'Your appointment booking invoice',

    // Common Symptoms
    'symptoms.fever': 'Fever',
    'symptoms.cough': 'Cough',
    'symptoms.coldFlu': 'Cold / Flu',
    'symptoms.headache': 'Headache',
    'symptoms.stomachache': 'Stomach Pain / Abdominal Pain',
    'symptoms.bodyPain': 'Body Pain / Weakness',
    'symptoms.chestPain': 'Chest Pain',
    'symptoms.breathingDifficulty': 'Breathing Difficulty',
    'symptoms.dizziness': 'Dizziness / Vertigo',
    'symptoms.nausea': 'Nausea / Vomiting',
    'symptoms.skinRash': 'Skin Rash / Allergy',
    'symptoms.eyeProblems': 'Eye Problems',
    'symptoms.earPain': 'Ear Pain',
    'symptoms.toothache': 'Toothache / Dental Issue',
    'symptoms.backPain': 'Back Pain',
    'symptoms.jointPain': 'Joint Pain / Arthritis',
    'symptoms.diabetes': 'Diabetes Checkup',
    'symptoms.bloodPressure': 'Blood Pressure Checkup',
    'symptoms.injury': 'Injury / Accident',
    'symptoms.checkup': 'General Checkup',
    'symptoms.other': 'Other (Specify)',

    // Ambulance
    'ambulance.title': 'Emergency Ambulance Service',
    'ambulance.available': 'ambulances available',
    'ambulance.smartDispatch': 'Smart dispatch system',
    'ambulance.autoDispatch': 'System automatically dispatches the',
    'ambulance.nearestAmbulance': 'nearest available ambulance',
    'ambulance.whenRequest': 'when you request emergency service.',
    'ambulance.detectLocation': 'Detect My Location',
    'ambulance.locationDetected': 'Location Detected ✓',
    'ambulance.gettingLocation': 'Getting Location...',
    'ambulance.location': 'Location',
    'ambulance.locationSuccess': 'Location detected successfully',
    'ambulance.locationError': 'Could not get your location',
    'ambulance.locationErrorDesc': 'Using default distances. Please enable location services for accurate results.',
    'ambulance.geolocationNotSupported': 'Geolocation is not supported by your browser',
    'ambulance.patientName': 'Patient Name',
    'ambulance.enterPatientName': 'Enter patient name for emergency pickup',
    'ambulance.phoneNumber': 'Phone Number',
    'ambulance.enterPhoneNumber': 'Enter contact number',
    'ambulance.requestEmergency': 'Request Emergency Ambulance',
    'ambulance.dispatchNearest': 'Dispatch Nearest Ambulance',
    'ambulance.noAvailable': 'No ambulances available',
    'ambulance.allDispatched': 'All ambulances are currently dispatched',
    'ambulance.dispatchSuccess': 'Ambulance dispatched!',
    'ambulance.ambulanceId': 'Ambulance ID',
    'ambulance.eta': 'ETA',
    'ambulance.minutes': 'minutes',
    'ambulance.returned': 'Ambulance returned to base',
    'ambulance.nowAvailable': 'is now available',
    'ambulance.fleetStatus': 'Ambulance Fleet Status',
    'ambulance.driver': 'Driver',
    'ambulance.available.status': 'Available',
    'ambulance.dispatched': 'Dispatched',
    'ambulance.kmAway': 'km away',
    'ambulance.onMission': 'On mission for:',
    'ambulance.dispatchedAt': 'Dispatched',
    'ambulance.markReturned': 'Mark as Returned',

    // Payment
    'payment.title': 'Payment',
    'payment.subtitle': 'Complete your payment to confirm booking',
    'payment.totalAmount': 'Total Amount',
    'payment.selectMethod': 'Select Payment Method',
    'payment.card': 'Credit/Debit Card',
    'payment.upi': 'UPI',
    'payment.cash': 'Cash',
    'payment.insurance': 'Insurance',
    'payment.cardNumber': 'Card Number',
    'payment.cardName': 'Cardholder Name',
    'payment.expiry': 'Expiry (MM/YY)',
    'payment.cvv': 'CVV',
    'payment.upiId': 'UPI ID',
    'payment.insurancePolicy': 'Insurance Policy Number',
    'payment.insuranceProvider': 'Insurance Provider',
    'payment.cancel': 'Cancel',
    'payment.pay': 'Pay',
    'payment.processing': 'Processing...',
    'payment.secure': 'Your payment information is secure and encrypted',

    // Invoice
    'invoice.title': 'Invoice',
    'invoice.billTo': 'Bill To:',
    'invoice.serviceType': 'Service Type:',
    'invoice.description': 'Description',
    'invoice.quantity': 'Qty',
    'invoice.unitPrice': 'Unit Price',
    'invoice.total': 'Total',
    'invoice.subtotal': 'Subtotal:',
    'invoice.discount': 'Discount:',
    'invoice.tax': 'Tax (18% GST):',
    'invoice.grandTotal': 'Total:',
    'invoice.paymentDetails': 'Payment Details',
    'invoice.method': 'Method:',
    'invoice.status': 'Status:',
    'invoice.transactionId': 'Transaction ID:',
    'invoice.download': 'Download PDF',
    'invoice.email': 'Email Invoice',
    'invoice.paid': 'Paid',
    'invoice.pending': 'Pending',

    // Profile
    'profile.title': 'My Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.patient': 'अपॉइंटमेंट बुक करें',
    'nav.doctor': 'डॉक्टर डैशबोर्ड',
    'nav.pharmacy': 'फार्मेसी',
    'nav.beds': 'बेड प्रबंधन',
    'nav.ambulance': 'एम्बुलेंस',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'प्रोफाइल',

    // Login Page
    'login.title': 'क्लिनिककेयर लॉगिन',
    'login.subtitle': 'अपने स्वास्थ्य पोर्टल तक पहुंचें',
    'login.signin': 'साइन इन',
    'login.signup': 'साइन अप',
    'login.description': 'अपनी भूमिका चुनें और अपनी जानकारी दर्ज करें',
    'login.patient': 'रोगी',
    'login.doctor': 'डॉक्टर',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'login.fullName': 'पूरा नाम',
    'login.phone': 'फोन नंबर',
    'login.signinButton': 'साइन इन करें',
    'login.signupButton': 'साइन अप करें',
    'login.signingIn': 'साइन इन हो रहा है...',
    'login.signingUp': 'साइन अप हो रहा है...',
    'login.haveAccount': 'पहले से खाता है?',
    'login.noAccount': 'खाता नहीं है?',
    'login.sessionExpiry': 'सत्र 5 मिनट की निष्क्रियता के बाद समाप्त हो जाएगा',
    'login.patientAccess': 'रोगी पोर्टल एक्सेस:',
    'login.patientDesc': 'अपॉइंटमेंट बुक करें, मेडिकल हिस्ट्री देखें और प्रिस्क्रिप्शन मैनेज करें',
    'login.doctorAccess': 'डॉक्टर पोर्टल एक्सेस:',
    'login.doctorDesc': 'अपॉइंटमेंट मैनेज करें, प्रिस्क्रिप्शन लिखें और रोगी रिकॉर्ड देखें',

    // Home Page
    'home.title': 'क्लिनिककेयर प्रबंधन प्रणाली',
    'home.subtitle': 'स्मार्ट कतार प्रबंधन, आपातकालीन सेवाएं और निर्बाध रोगी देखभाल समन्वय',
    'home.welcomeBack': 'वापसी पर स्वागत है',
    'home.myAppointments': 'मेरी अपॉइंटमेंट',
    'home.ourServices': 'हमारी सेवाएं',
    'home.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'home.doctorPortal': 'डॉक्टर पोर्टल',
    'home.patientsServed': 'मरीजों की सेवा की',
    'home.expertDoctors': 'विशेषज्ञ डॉक्टर',
    'home.hospitalBeds': 'अस्पताल बेड',
    'home.service247': '24/7 सेवा',
    'home.always': 'हमेशा',
    'home.patientAppointments': 'रोगी अपॉइंटमेंट',
    'home.patientAppointmentsDesc': 'पसंदीदा डॉक्टर और समय स्लॉट के साथ अपॉइंटमेंट बुक करें',
    'home.doctorDashboard': 'डॉक्टर डैशबोर्ड',
    'home.doctorDashboardDesc': 'अपॉइंटमेंट मैनेज करें, प्रिस्क्रिप्शन लिखें और रोगी देखभाल',
    'home.pharmacy': 'फार्मेसी',
    'home.pharmacyDesc': 'प्रिस्क्रिप्शन प्रबंधन और दवा इन्वेंट्री ट्रैकिंग',
    'home.bedManagement': 'बेड प्रबंधन',
    'home.bedManagementDesc': 'रियल-टाइम बेड उपलब्धता और आरक्षण प्रणाली',
    'home.emergencyAmbulance': 'आपातकालीन एम्बुलेंस',
    'home.emergencyAmbulanceDesc': 'निकटतम एम्बुलेंस के लिए स्मार्ट डिस्पैच सिस्टम',
    'home.smartQueue': 'स्मार्ट कतार एल्गोरिथम',
    'home.smartQueueDesc': 'इष्टतम रोगी देखभाल के लिए बुद्धिमान प्राथमिकता',
    'home.priority1': 'ला',
    'home.priority2': 'रा',
    'home.priority3': 'रा',
    'home.urgencyLevel': 'तात्कालिकता स्तर',
    'home.criticalCases': 'गंभीर मामलों को प्राथमिकता',
    'home.seniorCitizens': 'वरिष्ठ नागरिक',
    'home.age60Plus': '60+ उम्र को प्राथमिकता',
    'home.appointmentTime': 'अपॉइंटमेंट समय',
    'home.earlierSlots': 'पहले के स्लॉट पहले सेवा',

    // Patient Booking
    'booking.title': 'अपॉइंटमेंट बुक करें',
    'booking.subtitle': 'परामर्श निर्धारित करने के लिए अपना विवरण भरें',
    'booking.patientName': 'रोगी का नाम',
    'booking.enterName': 'पूरा नाम दर्ज करें',
    'booking.age': 'उम्र',
    'booking.enterAge': 'उम्र दर्ज करें',
    'booking.phone': 'फोन नंबर',
    'booking.enterPhone': 'फोन दर्ज करें',
    'booking.email': 'ईमेल',
    'booking.enterEmail': 'ईमेल पता दर्ज करें',
    'booking.issue': 'चिकित्सा समस्या / कारण',
    'booking.selectSymptom': 'अपना लक्षण चुनें',
    'booking.describeSymptom': 'अपने लक्षण या यात्रा का कारण बताएं',
    'booking.urgency': 'तात्कालिकता स्तर',
    'booking.urgencyLow': 'कम - नियमित जांच',
    'booking.urgencyMedium': 'मध्यम - मानक परामर्श',
    'booking.urgencyHigh': 'उच्च - तत्काल ध्यान आवश्यक',
    'booking.urgencyCritical': 'गंभीर - आपातकाल',
    'booking.preferredDoctor': 'पसंदीदा डॉक्टर',
    'booking.selectDoctor': 'डॉक्टर चुनें',
    'booking.timeSlot': 'पसंदीदा समय स्लॉट',
    'booking.continuePayment': 'भुगतान जारी रखें',
    'booking.fillAllFields': 'कृपया सभी फील्ड भरें',
    'booking.validAge': 'कृपया वैध उम्र दर्ज करें',
    'booking.bookingSuccess': 'अपॉइंटमेंट सफलतापूर्वक बुक हुई!',
    'booking.pendingApproval': 'आपकी अपॉइंटमेंट डॉक्टर की मंजूरी की प्रतीक्षा में है।',
    'booking.appointmentId': 'अपॉइंटमेंट आईडी',
    'booking.consultationFee': 'परामर्श शुल्क',
    'booking.urgencyAppointment': 'तात्कालिकता अपॉइंटमेंट',
    'booking.invoiceDescription': 'आपकी अपॉइंटमेंट बुकिंग का बीजक',

    // Common Symptoms
    'symptoms.fever': 'बुखार',
    'symptoms.cough': 'खांसी',
    'symptoms.coldFlu': 'सर्दी / फ्लू',
    'symptoms.headache': 'सिरदर्द',
    'symptoms.stomachache': 'पेट दर्द / पेट में दर्द',
    'symptoms.bodyPain': 'शरीर में दर्द / कमजोरी',
    'symptoms.chestPain': 'छाती में दर्द',
    'symptoms.breathingDifficulty': 'सांस लेने में कठिनाई',
    'symptoms.dizziness': 'चक्कर आना',
    'symptoms.nausea': 'मतली / उल्टी',
    'symptoms.skinRash': 'त्वचा पर चकत्ते / एलर्जी',
    'symptoms.eyeProblems': 'आंखों की समस्या',
    'symptoms.earPain': 'कान में दर्द',
    'symptoms.toothache': 'दांत दर्द / दांत की समस्या',
    'symptoms.backPain': 'पीठ दर्द',
    'symptoms.jointPain': 'जोड़ों का दर्द / गठिया',
    'symptoms.diabetes': 'मधुमेह जांच',
    'symptoms.bloodPressure': 'रक्तचाप जांच',
    'symptoms.injury': 'चोट / दुर्घटना',
    'symptoms.checkup': 'सामान्य जांच',
    'symptoms.other': 'अन्य (निर्दिष्ट करें)',

    // Ambulance
    'ambulance.title': 'आपातकालीन एम्बुलेंस सेवा',
    'ambulance.available': 'एम्बुलेंस उपलब्ध',
    'ambulance.detectLocation': 'मेरा स्थान पता लगाएं',
    'ambulance.locationDetected': 'स्थान का पता चला ✓',
    'ambulance.gettingLocation': 'स्थान प्राप्त कर रहे हैं...',
    'ambulance.requestEmergency': 'आपातकालीन एम्बुलेंस का अनुरोध करें',
    'ambulance.dispatchNearest': 'निकटतम एम्बुलेंस भेजें',
    'ambulance.fleetStatus': 'एम्बुलेंस फ्लीट स्थिति',
    'ambulance.driver': 'ड्राइवर',
    'ambulance.available.status': 'उपलब्ध',
    'ambulance.dispatched': 'भेजा गया',
    'ambulance.onMission': 'मिशन पर:',
    'ambulance.markReturned': 'वापस आया हुआ चिह्नित करें',

    // Payment
    'payment.title': 'भुगतान',
    'payment.subtitle': 'बुकिंग की पुष्टि के लिए अपना भुगतान पूरा करें',
    'payment.totalAmount': 'कुल राशि',
    'payment.selectMethod': 'भुगतान विधि चुनें',
    'payment.card': 'क्रेडिट/डेबिट कार्ड',
    'payment.upi': 'यूपीआई',
    'payment.cash': 'नकद',
    'payment.insurance': 'बीमा',
    'payment.cardNumber': 'कार्ड नंबर',
    'payment.cardName': 'कार्डधारक का नाम',
    'payment.expiry': 'समाप्ति (MM/YY)',
    'payment.cvv': 'सीवीवी',
    'payment.upiId': 'यूपीआई आईडी',
    'payment.insurancePolicy': 'बीमा पॉलिसी नंबर',
    'payment.insuranceProvider': 'बीमा प्रदाता',
    'payment.cancel': 'रद्द करें',
    'payment.pay': 'भुगतान करें',
    'payment.processing': 'प्रक्रिया जारी है...',
    'payment.secure': 'आपकी भुगतान जानकारी सुरक्षित और एन्क्रिप्टेड है',

    // Invoice
    'invoice.title': 'चालान',
    'invoice.billTo': 'बिल प्राप्तकर्ता:',
    'invoice.serviceType': 'सेवा प्रकार:',
    'invoice.description': 'विवरण',
    'invoice.quantity': 'मात्रा',
    'invoice.unitPrice': 'इकाई मूल्य',
    'invoice.total': 'कुल',
    'invoice.subtotal': 'उप-योग:',
    'invoice.discount': 'छूट:',
    'invoice.tax': 'कर (18% जीएसटी):',
    'invoice.grandTotal': 'कुल:',
    'invoice.paymentDetails': 'भुगतान विवरण',
    'invoice.method': 'विधि:',
    'invoice.status': 'स्थिति:',
    'invoice.transactionId': 'लेनदेन आईडी:',
    'invoice.download': 'पीडीएफ डाउनलोड करें',
    'invoice.email': 'ईमेल चालान',
    'invoice.paid': 'भुगतान किया गया',
    'invoice.pending': 'लंबित',

    // Profile
    'profile.title': 'मेरी प्रोफ़ाइल',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.name': 'नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन',
    'profile.role': 'भूमिका',
    'profile.edit': 'प्रोफ़ाइल संपादित करें',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.cancel': 'रद्द करें',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.currentPassword': 'वर्तमान पासवर्ड',
    'profile.newPassword': 'नया पासवर्ड',
    'profile.confirmNewPassword': 'नया पासवर्ड की पुष्टि करें',

    // Common
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.submit': 'जमा करें',
    'common.loading': 'लोड हो रहा है...',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
  },
  mr: {
    // Navigation
    'nav.home': 'होम',
    'nav.patient': 'भेट बुक करा',
    'nav.doctor': 'डॉक्टर डॅशबोर्ड',
    'nav.pharmacy': 'फार्मसी',
    'nav.beds': 'बेड व्यवस्थापन',
    'nav.ambulance': 'रुग्णवाहिका',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'प्रोफाइल',

    // Login Page
    'login.title': 'क्लिनिककेअर लॉगिन',
    'login.subtitle': 'तुमच्या आरोग्य पोर्टलमध्ये प्रवेश करा',
    'login.signin': 'साइन इन',
    'login.signup': 'साइन अप',
    'login.description': 'तुमची भूमिका निवडा आणि तुमची माहिती प्रविष्ट करा',
    'login.patient': 'रुग्ण',
    'login.doctor': 'डॉक्टर',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.confirmPassword': 'पासवर्डची पुष्टी करा',
    'login.fullName': 'पूर्ण नाव',
    'login.phone': 'फोन नंबर',
    'login.signinButton': 'साइन इन करा',
    'login.signupButton': 'साइन अप करा',
    'login.signingIn': 'साइन इन होत आहे...',
    'login.signingUp': 'साइन अप होत आहे...',
    'login.haveAccount': 'आधीच खाते आहे?',
    'login.noAccount': 'खाते नाही?',
    'login.sessionExpiry': 'सत्र 5 मिनिटांच्या निष्क्रियतेनंतर संपेल',
    'login.patientAccess': 'रुग्ण पोर्टल प्रवेश:',
    'login.patientDesc': 'भेटी बुक करा, वैद्यकीय इतिहास पहा आणि प्रिस्क्रिप्शन व्यवस्थापित करा',
    'login.doctorAccess': 'डॉक्टर पोर्टल प्रवेश:',
    'login.doctorDesc': 'भेटी व्यवस्थापित करा, प्रिस्क्रिप्शन लिहा आणि रुग्ण नोंदी पहा',

    // Home Page
    'home.title': 'क्लिनिककेअर व्यवस्थापन प्रणाली',
    'home.subtitle': 'स्मार्ट रांग व्यवस्थापन, आपत्कालीन सेवा आणि अखंड रुग्ण काळजी समन्वय',
    'home.welcomeBack': 'परत स्वागत आहे',
    'home.myAppointments': 'माझ्या भेटी',
    'home.ourServices': 'आमच्या सेवा',
    'home.bookAppointment': 'भेट बुक करा',
    'home.doctorPortal': 'डॉक्टर पोर्टल',
    'home.patientsServed': 'रुग्णांची सेवा केली',
    'home.expertDoctors': 'तज्ञ डॉक्टर',
    'home.hospitalBeds': 'हॉस्पिटल बेड',
    'home.service247': '24/7 सेवा',
    'home.always': 'नेहमी',
    'home.patientAppointments': 'रुग्ण भेटी',
    'home.patientAppointmentsDesc': 'पसंतीच्या डॉक्टर आणि वेळेसह भेटी बुक करा',
    'home.doctorDashboard': 'डॉक्टर डॅशबोर्ड',
    'home.doctorDashboardDesc': 'भेटी व्यवस्थापित करा, प्रिस्क्रिप्शन लिहा आणि रुग्ण काळजी',
    'home.pharmacy': 'फार्मसी',
    'home.pharmacyDesc': 'प्रिस्क्रिप्शन व्यवस्थापन आणि औषध इन्व्हेंटरी ट्रॅकिंग',
    'home.bedManagement': 'बेड व्यवस्थापन',
    'home.bedManagementDesc': 'रिअल-टाइम बेड उपलब्धता आणि आरक्षण प्रणाली',
    'home.emergencyAmbulance': 'आपत्कालीन रुग्णवाहिका',
    'home.emergencyAmbulanceDesc': 'जवळच्या रुग्णवाहिकेसाठी स्मार्ट डिस्पॅच सिस्टम',
    'home.smartQueue': 'स्मार्ट रांग अल्गोरिदम',
    'home.smartQueueDesc': 'इष्टतम रुग्ण काळजीसाठी बुद्धिमान प्राधान्यता',
    'home.priority1': 'ला',
    'home.priority2': 'रा',
    'home.priority3': 'रा',
    'home.urgencyLevel': 'तातडीचा स्तर',
    'home.criticalCases': 'गंभीर प्रकरणांना प्राधान्य',
    'home.seniorCitizens': 'ज्येष्ठ नागरिक',
    'home.age60Plus': '60+ वयाला प्राधान्य',
    'home.appointmentTime': 'भेटीची वेळ',
    'home.earlierSlots': 'आधीचे स्लॉट प्रथम सेवा',

    // Patient Booking
    'booking.title': 'भेट बुक करा',
    'booking.subtitle': 'सल्लामसलत नियोजित करण्यासाठी तुमचे तपशील भरा',
    'booking.patientName': 'रुग्णाचे नाव',
    'booking.enterName': 'पूर्ण नाव प्रविष्ट करा',
    'booking.age': 'वय',
    'booking.enterAge': 'वय प्रविष्ट करा',
    'booking.phone': 'फोन नंबर',
    'booking.enterPhone': 'फोन प्रविष्ट करा',
    'booking.email': 'ईमेल',
    'booking.enterEmail': 'ईमेल पत्ता प्रविष्ट करा',
    'booking.issue': 'वैद्यकीय समस्या / कारण',
    'booking.selectSymptom': 'तुमचे लक्षण निवडा',
    'booking.describeSymptom': 'तुमची लक्षणे किंवा भेटीचे कारण सांगा',
    'booking.urgency': 'तातडीचा स्तर',
    'booking.urgencyLow': 'कमी - नियमित तपासणी',
    'booking.urgencyMedium': 'मध्यम - मानक सल्लामसलत',
    'booking.urgencyHigh': 'उच्च - तात्काळ लक्ष आवश्यक',
    'booking.urgencyCritical': 'गंभीर - आपत्कालीन',
    'booking.preferredDoctor': 'पसंतीचे डॉक्टर',
    'booking.selectDoctor': 'डॉक्टर निवडा',
    'booking.timeSlot': 'पसंतीचा वेळ',
    'booking.continuePayment': 'पेमेंट सुरू ठेवा',
    'booking.fillAllFields': 'कृपया सर्व फील्ड भरा',
    'booking.validAge': 'कृपया वैध वय प्रविष्ट करा',
    'booking.bookingSuccess': 'भेट यशस्वीरित्या बुक झाली!',
    'booking.pendingApproval': 'तुमची भेट डॉक्टरांच्या मंजुरीच्या प्रतीक्षेत आहे।',
    'booking.appointmentId': 'भेट आयडी',
    'booking.consultationFee': 'सल्लामसलत शुल्क',
    'booking.urgencyAppointment': 'तातडी भेट',
    'booking.invoiceDescription': 'तुमच्या भेट बुकिंगचे बीजक',

    // Common Symptoms
    'symptoms.fever': 'ताप',
    'symptoms.cough': 'खोकला',
    'symptoms.coldFlu': 'सर्दी / फ्लू',
    'symptoms.headache': 'डोकेदुखी',
    'symptoms.stomachache': 'पोटदुखी',
    'symptoms.bodyPain': 'शरीर दुखी / कमकुवतपणा',
    'symptoms.chestPain': 'छातीत दुखणे',
    'symptoms.breathingDifficulty': 'श्वास घेण्यात अडचण',
    'symptoms.dizziness': 'चक्कर येणे',
    'symptoms.nausea': 'मळमळ / उलट्या',
    'symptoms.skinRash': 'त्वचेवर पुरळ / ऍलर्जी',
    'symptoms.eyeProblems': 'डोळ्यांच्या समस्या',
    'symptoms.earPain': 'कानात दुखणे',
    'symptoms.toothache': 'दात दुखणे / दंत समस्या',
    'symptoms.backPain': 'पाठदुखी',
    'symptoms.jointPain': 'सांधेदुखी / संधिवात',
    'symptoms.diabetes': 'मधुमेह तपासणी',
    'symptoms.bloodPressure': 'रक्तदाब तपासणी',
    'symptoms.injury': 'दुखापत / अपघात',
    'symptoms.checkup': 'सामान्य तपासणी',
    'symptoms.other': 'इतर (निर्दिष्ट करा)',

    // Ambulance
    'ambulance.title': 'आपत्कालीन रुग्णवाहिका सेवा',
    'ambulance.available': 'रुग्णवाहिका उपलब्ध',
    'ambulance.detectLocation': 'माझे स्थान शोधा',
    'ambulance.locationDetected': 'स्थान सापडले ✓',
    'ambulance.gettingLocation': 'स्थान मिळवत आहे...',
    'ambulance.requestEmergency': 'आपत्कालीन रुग्णवाहिकेची विनंती करा',
    'ambulance.dispatchNearest': 'जवळची रुग्णवाहिका पाठवा',
    'ambulance.fleetStatus': 'रुग्णवाहिका फ्लीट स्थिती',
    'ambulance.driver': 'ड्रायव्हर',
    'ambulance.available.status': 'उपलब्ध',
    'ambulance.dispatched': 'पाठवले',
    'ambulance.onMission': 'मिशनवर:',
    'ambulance.markReturned': 'परत आले म्हणून चिन्हांकित करा',

    // Payment
    'payment.title': 'पेमेंट',
    'payment.subtitle': 'बुकिंगची पुष्टी करण्यासाठी तुमचे पेमेंट पूर्ण करा',
    'payment.totalAmount': 'एकूण रक्कम',
    'payment.selectMethod': 'पेमेंट पद्धत निवडा',
    'payment.card': 'क्रेडिट/डेबिट कार्ड',
    'payment.upi': 'यूपीआय',
    'payment.cash': 'रोख',
    'payment.insurance': 'विमा',
    'payment.cardNumber': 'कार्ड नंबर',
    'payment.cardName': 'कार्डधारकाचे नाव',
    'payment.expiry': 'समाप्ती (MM/YY)',
    'payment.cvv': 'सीव्हीव्ही',
    'payment.upiId': 'यूपीआय आयडी',
    'payment.insurancePolicy': 'विमा पॉलिसी नंबर',
    'payment.insuranceProvider': 'विमा प्रदाता',
    'payment.cancel': 'रद्द करा',
    'payment.pay': 'पेमेंट करा',
    'payment.processing': 'प्रक्रिया सुरू आहे...',
    'payment.secure': 'तुमची पेमेंट माहिती सुरक्षित आणि एनक्रिप्टेड आहे',

    // Invoice
    'invoice.title': 'बीजक',
    'invoice.billTo': 'बिल प्राप्तकर्ता:',
    'invoice.serviceType': 'सेवा प्रकार:',
    'invoice.description': 'वर्णन',
    'invoice.quantity': 'प्रमाण',
    'invoice.unitPrice': 'एकक किंमत',
    'invoice.total': 'एकूण',
    'invoice.subtotal': 'उप-योग:',
    'invoice.discount': 'सूट:',
    'invoice.tax': 'कर (18% जीएसटी):',
    'invoice.grandTotal': 'एकूण:',
    'invoice.paymentDetails': 'पेमेंट तपशील',
    'invoice.method': 'पद्धत:',
    'invoice.status': 'स्थिती:',
    'invoice.transactionId': 'व्यवहार आयडी:',
    'invoice.download': 'पीडीएफ डाउनलोड करा',
    'invoice.email': 'ईमेल बीजक',
    'invoice.paid': 'पेमेंट झाले',
    'invoice.pending': 'प्रलंबित',

    // Profile
    'profile.title': 'माझी प्रोफाइल',
    'profile.personalInfo': 'वैयक्तिक माहिती',
    'profile.name': 'नाव',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन',
    'profile.role': 'भूमिका',
    'profile.edit': 'प्रोफाइल संपादित करा',
    'profile.save': 'बदल सेव्ह करा',
    'profile.cancel': 'रद्द करा',
    'profile.changePassword': 'पासवर्ड बदला',
    'profile.currentPassword': 'सध्याचा पासवर्ड',
    'profile.newPassword': 'नवीन पासवर्ड',
    'profile.confirmNewPassword': 'नवीन पासवर्डची पुष्टी करा',

    // Common
    'common.save': 'सेव्ह करा',
    'common.cancel': 'रद्द करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.submit': 'सबमिट करा',
    'common.loading': 'लोड होत आहे...',
    'common.search': 'शोधा',
    'common.filter': 'फिल्टर',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
